### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by somenonymous** [somenonymous/OshiUpload#6]
- [x] Migrate PUT uploads to Mojolicious
- [ ] Web Crypto API  (https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API)
- [ ] Uploads from URL to mirror stuff
- [ ] Migrate config to YAML
- [ ] Proper error and exception logging
- [x] add custom HTTP methods for file management to ease console access
- [x] UA detection for console browsers so they are given text instead of HTML (not found pages etc)
- [ ] Automatic low space detection - delete oldest files when free space is less than X MB (defined by config) until X MB amount of space becomes available

This topic is also open for new feature suggestions.
